name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: pnpm
            
      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🛠 Build
        run: pnpm build

      - name: 💪 Lint
        run: pnpm lint